spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

# 스프링 부트 타임리프 기본 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    open-in-view: false #OSIV OFF
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true #System.out에 하이버네이트 실행 SQL 출력(운영 환경에서는 System.out에 찍으면 안되고)
        format_sql: true
        default_batch_fetch_size: 100 #지연 로딩 성능 최적화를 위한 글로벌 설정, 컬렉션이나 프록시 객체를 한꺼번에 설정한 size 만큼 IN 쿼리로 조회

logging:
  level:
    org.hibernate.SQL: debug #Logger를 통해서 하이버네이트 실행 SQL 출력(모든 로그 출력은 가급적 로거를 통해 남겨야 한다.)
#    org.hibernate.type: trace #SQL 실행 파라미터를 로그로 출력