spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      naming:
        physical-strategy: jpabook.jpashop.CustomSpringPhysicalNamingStrategy #테이블, 컬럼명 생성 전략을 회사 룰로 변경 가능
      ddl-auto: create-drop # Create the schema and destroy previous data
    properties:
      hibernate:
#        show_sql: true #System.out에 하이버네이트 실행 SQL 출력(운영 환경에서는 System.out에 찍으면 안되고)
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #Logger를 통해서 하이버네이트 실행 SQL 출력(모든 로그 출력은 가급적 로거를 통해 남겨야 한다.)
#    org.hibernate.type: trace #SQL 실행 파라미터를 로그로 출력